services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api:
        condition: service_healthy
      web:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - csmart-network

  api:
    image: ghcr.io/nguyendkn/turborepo/api:main-22673e5
    expose:
      - '3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URI=
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-at-least-32-characters-long
      - JWT_EXPIRES_IN=24h
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-at-least-32-characters-long
      - JWT_REFRESH_EXPIRES_IN=7d
      - CORS_ORIGINS=
      - CORS_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_HEADERS=Content-Type,Authorization
      - CORS_CREDENTIALS=true
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your-email@gmail.com
      - SMTP_PASSWORD=your-app-password
      - SMTP_FROM=noreply@csmart.com
      - MAX_FILE_SIZE=10485760
      - UPLOAD_DIR=/uploads
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - API_DOCS_ENABLED=false
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://127.0.0.1:3000/',
        ]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 60s
    restart: unless-stopped
    networks:
      - csmart-network

  web:
    image: ghcr.io/nguyendkn/turborepo/web:main-22673e5
    expose:
      - '80'
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://127.0.0.1/',
        ]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 60s
    restart: unless-stopped
    networks:
      - csmart-network

networks:
  csmart-network:
    driver: bridge
